### ISSUE TITLE
Error approving the node csr Temporary Error: exit status 1

### ISSUE THREAD

**Issue by arprakas** [code-ready/crc#1039]
Got the above error message while I attempted to do crc start on mac OS Catalina. Let me know if you need anything from my end. Thanks!

**Comment by gbraad** [comment]
Does not follow issue template. Please provide requested information.

**Comment by arprakas** [comment]
**General Information**

- OS: macOS Catalina
- Hypervisor: hyperkit
- Did you run crc setup before starting it (Yes/No)? Yes

**CRC version**
# Put the output of `crc version`
crc version: 1.6.0+8ef676f
OpenShift version: 4.3.0 (embedded in binary)

**CRC status**
# Put the output of `crc status`
ERRO The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port?
 - exit status 1 

**CRC config**
# Put the output of `crc config view`
Modifies crc configuration properties.
Configurable properties (enter as SUBCOMMAND): 

 * bundle
 * cpus
 * disable-update-check
 * enable-experimental-features
 * http-proxy
 * https-proxy
 * memory
 * nameserver
 * no-proxy
 * pull-secret-file
 * skip-check-bundle-cached
 * warn-check-bundle-cached
 * skip-check-hosts-file-permissions
 * warn-check-hosts-file-permissions
 * skip-check-hyperkit-driver
 * warn-check-hyperkit-driver
 * skip-check-hyperkit-installed
 * warn-check-hyperkit-installed
 * skip-check-resolver-file-permissions
 * warn-check-resolver-file-permissions
 * skip-check-root-user
 * warn-check-root-user

Usage:
  crc config SUBCOMMAND [flags]
  crc config [command]

Available Commands:
  get         Get a crc configuration property
  set         Set a crc configuration property
  unset       Unset a crc configuration property
  view        Display all assigned crc configuration properties

Flags:
  -h, --help   help for config

Global Flags:
  -f, --force              Forcefully perform an action
      --log-level string   log level (e.g. "debug | info | warn | error") (default "info")

Use "crc config [command] --help" for more information about a command.


**Host Operating System**
# put the output of `sw_vers` in case of Mac
ProductName:	Mac OS X
ProductVersion:	10.15.3
BuildVersion:	19D76

**Steps to reproduce**

crc start


ERROR:
INFO Checking if oc binary is cached              
INFO Checking if running as non-root              
INFO Checking if HyperKit is installed            
INFO Checking if crc-driver-hyperkit is installed 
INFO Checking file permissions for /etc/resolver/testing 
INFO Checking file permissions for /etc/hosts     
INFO Starting CodeReady Containers VM for OpenShift 4.3.0... 
INFO Verifying validity of the cluster certificates ... 
INFO Network restart not needed                   
INFO Check internal and public DNS query ...      
INFO Check DNS query from host ...                
ERRO Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1 


Please let me know if you need anything else.

**Comment by gbraad** [comment]
@praveenkumar @anjannath seems network settings are OK. Any thoughts?

**Comment by praveenkumar** [comment]
@arprakas can you try following and put the result in a gist? 

```
$ crc delete
$ crc start --log-level debug
```

**Comment by smushigo** [comment]
same error for me. 
macOS 10.15.4

**Comment by smushigo** [comment]
crc delete  
crc start -p pull-secret  --log-level debug

It failed with the following error

DEBU Command failed: exit status 1                
DEBU stdout:                                      
DEBU stderr: The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
DEBU The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
DEBU error: Temporary Error: exit status 1 - sleeping 1s

**Comment by sb1975** [comment]
I got similar error as well. OS : Centos 7.8 (CentOS Linux release 7.8.2003 (Core)

INFO Check DNS query from host ...
INFO Copying kubeconfig file to instance dir ...
INFO Adding user's pull secret ...
INFO Updating cluster ID ...
INFO Starting OpenShift cluster ... [waiting 3m]






ERRO Error approving the node csr Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1
Temporary Error: exit status 1

**Comment by kz12123** [comment]
`INFO Configuring cluster for first start          
INFO Adding user's pull secret ...                
DEBU Creating /var/lib/kubelet/config.json with permissions 0600 in the CRC VM 
(crc) Calling .GetSSHHostname
(crc) DBG | GetIP called for crc
(crc) DBG | Getting current state...
(crc) DBG | IP address: 192.168.130.11
(crc) Calling .GetSSHPort
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /home/ubuntu/.crc/machines/crc/id_rsa (-rw-------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@192.168.130.11 -o IdentitiesOnly=yes -i /home/ubuntu/.crc/machines/crc/id_rsa -p 22] /usr/bin/ssh <nil>}
DEBU About to run SSH command with hidden output  
DEBU Running '/home/ubuntu/.crc/bin/oc get secret --kubeconfig /home/ubuntu/.crc/machines/crc/kubeconfig --context admin --cluster crc' 
DEBU Command failed: exit status 1                
DEBU stdout:                                      
DEBU stderr: The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
DEBU The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
DEBU retry loop 1                                 
DEBU Running '/home/ubuntu/.crc/bin/oc get secret --kubeconfig /home/ubuntu/.crc/machines/crc/kubeconfig --context admin --cluster crc' 
DEBU Command failed: exit status 1                
DEBU stdout:                                      
DEBU stderr: The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
DEBU The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
DEBU retry loop 2                                 
DEBU Running '/home/ubuntu/.crc/bin/oc get secret --kubeconfig /home/ubuntu/.crc/machines/crc/kubeconfig --context admin --cluster crc' 
DEBU Command failed: exit status 1                
DEBU stdout:                                      
DEBU stderr: The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
DEBU The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
DEBU retry loop 3                                 
DEBU Running '/home/ubuntu/.crc/bin/oc get secret --kubeconfig /home/ubuntu/.crc/machines/crc/kubeconfig --context admin --cluster crc' 
DEBU Command failed: exit status 1                
DEBU stdout:                                      
DEBU stderr: The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
DEBU The connection to the server api.crc.testing:6443 was refused - did you specify the right host or port? 
DEBU error: Temporary Error: exit status 1 - sleeping 1s 
DEBU retry loop 4                                 
DEBU Running '/home/ubuntu/.crc/bin/oc get secret --kubeconfig /home/ubuntu/.crc/machines/crc/kubeconfig --context admin --cluster crc' 
DEBU NAME                       TYPE                                  DATA   AGE
builder-dockercfg-n48zx    kubernetes.io/dockercfg               1      18d
builder-token-b9pv8        kubernetes.io/service-account-token   4      18d
builder-token-r9hm2        kubernetes.io/service-account-token   4      18d
default-dockercfg-2n6n6    kubernetes.io/dockercfg               1      18d
default-token-lcfz2        kubernetes.io/service-account-token   4      18d
default-token-mt7jv        kubernetes.io/service-account-token   4      18d
deployer-dockercfg-sgmcp   kubernetes.io/dockercfg               1      18d
deployer-token-kphr6       kubernetes.io/service-account-token   4      18d
deployer-token-zkx5d       kubernetes.io/service-account-token   4      18d 
DEBU About to run a hidden command                
INFO Updating cluster ID ...                      
DEBU Running '/home/ubuntu/.crc/bin/oc get clusterversion --kubeconfig /home/ubuntu/.crc/machines/crc/kubeconfig --context admin --cluster crc' 
DEBU NAME      VERSION   AVAILABLE   PROGRESSING   SINCE   STATUS
version   4.4.3     True        False         18d     Cluster version is 4.4.3 
DEBU Running '/home/ubuntu/.crc/bin/oc patch clusterversion version -p {"spec":{"clusterID":"2be111b2-f883-4914-b79d-c0c786cca769"}} --type merge --kubeconfig /home/ubuntu/.crc/machines/crc/kubeconfig --context admin --cluster crc' 
(crc) Calling .GetSSHHostname
(crc) DBG | GetIP called for crc
(crc) DBG | Getting current state...
(crc) DBG | IP address: 192.168.130.11
(crc) Calling .GetSSHPort
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHKeyPath
(crc) Calling .GetSSHUsername
Using SSH client type: external
Using SSH private key: /home/ubuntu/.crc/machines/crc/id_rsa (-rw-------)
&{[-F /dev/null -o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@192.168.130.11 -o IdentitiesOnly=yes -i /home/ubuntu/.crc/machines/crc/id_rsa -p 22] /usr/bin/ssh <nil>}
DEBU About to run SSH command:
sudo systemctl -f is-active kubelet 
DEBU SSH cmd err, output: <nil>: active           
DEBU Waiting for update of client-ca request header ... 
DEBU Running '/home/ubuntu/.crc/bin/oc get configmaps --kubeconfig /home/ubuntu/.crc/machines/crc/kubeconfig --context admin --cluster crc' 
DEBU                                              
DEBU Running '/home/ubuntu/.crc/bin/oc get configmaps/extension-apiserver-authentication -ojsonpath={.data.requestheader-client-ca-file} -n kube-system --kubeconfig /home/ubuntu/.crc/machines/crc/kubeconfig --context admin --cluster crc' 
DEBU Found .data.requestheader-client-ca-file: -----BEGIN CERTIFICATE-----
XXXXXXX
-----END CERTIFICATE----- 
DEBU Running '/home/ubuntu/.crc/bin/oc get pod --kubeconfig /home/ubuntu/.crc/machines/crc/kubeconfig --context admin --cluster crc' 
DEBU                                              
DEBU Running '/home/ubuntu/.crc/bin/oc delete pod --all -n openshift-apiserver --kubeconfig /home/ubuntu/.crc/machines/crc/kubeconfig --context admin --cluster crc' 
INFO Starting OpenShift cluster ... [waiting 3m] `

**Comment by samiujan** [comment]
Similar problem with Ubuntu 18.04
