### ISSUE TITLE
Add support for multi-node deployment

### ISSUE THREAD

**Issue by danielBelenky** [code-ready/crc#1135]
In some cases, we might want to have more than one worker node in our cluster.
CRC have done a lot of work to make the deployment as easy as `crc start` and it would be great to be able to reuse this work for projects like https://github.com/kubevirt/kubevirt/ where we use various K8s/OCP providers for CI and development. The best situation for us would be when each of the worker nodes will run on a separate VM (to test migration for example).

**Comment by phoracek** [comment]
Adding requirements for network testing in kubevirt and related projects:
* Multi-node support
* Multi-NIC support (so we connect nodes with secondary interfaces, this should happen through L2 without tunneling, additional libvirt network is good enough for this)
* IPv6 support

**Comment by aglitke** [comment]
For storage we need:
* Configurable local storage for nodes (ability to set the amount of available storage per node)

**Comment by gbraad** [comment]
Kept around for reference. At the moment MNC is not the aim for CRC to handle. While technically possible and infrastructure is in place, there is currently no time. This would involve:

  * MNC generation script
  * handling DNS records (since IP is non-static)
  * allow adding and removing nodes

Resource usage would prevent this to be viable as a possible notebook scenario and therefore outside of our scope. Outside contributions are welcome, as this is valuable.
