### ISSUE TITLE
Kafka and AMQ setup on CRC

### ISSUE THREAD

**Issue by devopskarthikeyan** [code-ready/crc#1190]
Hi Gbraad,

Good morning .  I am having around 11 yrs exp in IT & currently working as Devops lead.  I would like to get some clarification about CRC kafka-amq setup .

We are having dedicated OCP setup in our client place with kafka&AMQ for our micro projects & its working fine .

So we tried replicate the same setup in our local env on CRC, Kafka&AMQ  it not working (https://github.com/red-hat-storage/ocs-training/tree/master/ocs4kafka - Setps followed from this redhat document)

Recently I saw you post on this link  https://github.com/code-ready/crc/issues/594 that “CRC does not work on kafka or amq so this would be hard for us to resolve.. I informed the team responsible for this and hopefully they will get back about this." Attached below comments screenshot”

Just want to know clarify that, can we able to make it kafa -amq on CRC?  If it is yes please provide setup document if applicable (we are using on windows10). If it is not then we will request our clients to get OCP instead CRC.

Kindly check and let me know please.

Thanks,
P.Karthikeyan

**Comment by gbraad** [comment]
I have clarified my answer here https://github.com/code-ready/crc/issues/594#issuecomment-531644112. We, as CRC, provide a production-like OpenShift cluster. We do not have the bandwidth to specifically look into issues ourselves with application ou that run on top of CRC, but rely on people providing feedback on possible issues that might occur because of 'disabling' operators. We do this to reduce the resource usage on the developer laptop use-case we work on.

Please continue the discussion on #594 (marking as dfuplicate).

**Comment by gbraad** [comment]
File an issue at: https://github.com/red-hat-storage/ocs-training/issues/157

**Comment by gbraad** [comment]
The user reports by email the following:

---

we are getting “ image pull backoff” error when we ran below command and container is not creating.
 
```
oc apply -f https://raw.githubusercontent.com/red-hat-storage/ocs-training/master/ocs4kafka/01-kafka-zookeeper.yaml
```
