### ISSUE TITLE
Document known issues

### ISSUE THREAD

**Issue by robin-owen** [code-ready/crc#131]
Add a new known issues "guide" to the docs. This would be a separate title from the getting started guide. (Place in `docs/source/known-issues`, maybe?)

What persistent known issues do we know about that we should document here?

**Comment by gbraad** [comment]
* The `marketplace` has been disabled which causes the OperatorHub to not function

**Comment by robin-owen** [comment]
* #127: Commands to resize the allocated memory, CPUs, and storage space.

We don't currently have any configuration options to use with `crc` _directly_ for these operations.

**Comment by jmazzitelli** [comment]
I was going to write this up as an individual issue (let me know if I should still do that), but right now I know of no way to push images directly to the container repository in the CRC VM. In other words, I'm thinking of something analogous to "minikube docker-env" where minikube gives you a simple environment change to make and then "docker push" simply pushes images to the minikube container repo. CRC needs this (this is what I am wondering if I should write a separate issue for).

But, since there isn't anything like that now in CRC, can we document some instructions on "This is how you can set up your host and the CRC VM to have images pushed from an external client into CRC's container repo".

This is useful for people doing development on their microservices - it would be nice to just build new images and push them directly to CRC's repo for OpenShift to pick up. The only obvious alternative is the annoying workflow of pushing to some public repo (like quay.io or docker.io) and then having CRC's OpenShift have to then pull from that public repo.

**Comment by robin-owen** [comment]
@jmazzitelli Go ahead and create a separate issue -- we can link to it here for documentation in the known issues.

Essentially, I'm using this issue as a "gathering place" for all of the known issues and limitations of CRC that we should document. :slightly_smiling_face:

Once I have a good list going, I'll add in a checklist to this issue.

@gbraad @praveenkumar By the way, the more I'm thinking about these limitations and how they must be configured at the moment, I'm starting to think that we could use a dedicated "Configuring CodeReady Containers" section of the documentation. I'd like to start keeping "known issues" limited to the scope of actual _issues_, not the current _limitations_ which we're planning to address in the future.

**Comment by robin-owen** [comment]
@gbraad @praveenkumar To add a little more context to what I said above, we can create an assembly for configuring CRC which will contain the needed commands **at the moment**, but in the future, will instead document how to configure CRC with the `crc` binary directly.

**Comment by valdar** [comment]
@jmazzitelli @robin-owen has a separate issue about "crc equivalent of minishift docker-env" been created? I have the same need as well as @nicolaferraro . Is there a documented "manual" way to achieve the same?

**Comment by gbraad** [comment]
CRC does not run docker so an equivalent is not available. However, a
possible podman-env is being worked on.
