### ISSUE TITLE
Make `crc cleanup` not fail on errors in macOS

### ISSUE THREAD

**Issue by anjannath** [code-ready/crc#1335]
The tray cleanup functions are returning error and stopping the cleanup, which it shouldn't as we want all the cleanups to run.

```bash
$ crc cleanup
INFO Unload CodeReady Containers tray             
FATA exit status 112
```

**Comment by anjannath** [comment]
Couldn't reproduce this on macOS 10.15 only happening in 10.14, maybe something to do with the version of`launchctl` ?

**Comment by cfergeau** [comment]
I haven't been able to reproduce on 10.14 either. Would be worth running the corresponding commands by hand.

**Comment by jsliacan** [comment]
I cannot replicate it now either. Agree with @anjannath though that:

> maybe something to do with the version of `launchctl`

The system was in some inconsistent state from which `crc cleanup` didn't work and `crc setup` didn't work either. 

Since we cannot readily replicate this, I'm happy to close the issue and hopefully we'll remember it if/when it resurfaces.
