### ISSUE TITLE
Handling cache cleanup

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#144]
At the moment all the bundles are extracted in the `~/.crc/cache` folder, but aren't cleaned up. A single bundle extracted takes up over 8+ GB of storage. We would need to include a command to remove these files; interactively or forced? Perhaps even report about this with a status command (#68) ?

**Comment by cfergeau** [comment]
Could this go to `~/.cache/crc` instead? This is standardized in https://specifications.freedesktop.org/basedir-spec/basedir-spec-latest.html and has the benefit of (for example) making it easier to ignore cache files in backups by ignoring ~/.cache as a whole, rather than having to explicitly add ~/.crc/cache
