### ISSUE TITLE
[BUG] when hypervisor delete fails, `delete -f` leaves machines definitions intact

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#1609]
When the hypervisor delete fails, like the VM has been manually deleted with Hyper-V manager, the machines defintion in `machines/crc` will remain in place:

```
PS C:\Users\gbraad\Downloads> & '.\crc.exe' delete -f
ERRO Driver cannot remove machine: exit status 1
Driver cannot remove machine: exit status 1
```

and therefore does not actually forcibly delete the VM anymore.

**Comment by cfergeau** [comment]
This is coming from https://github.com/code-ready/crc/blob/15ee02d3f749d43c44cabb43f56ce2811e0e8177/pkg/crc/machine/machine.go#L464-L466
There is a similar issue on linux. This could be fixed by returning a specific error from `libmachine.Driver.Remove` when the underlying VM does not exist, and ignoring that specific error in `crc` `machine.Delete()`

`crc cleanup` should not be impacted though, and remove both the VM and `~/.crc/machines`
