### ISSUE TITLE
Change code-ready/snc to use the single node cluster profile

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1682]
Once annotations and the CVO are in place, we can finally use the single node cluster profile in SNC.

**Comment by guillaumerose** [comment]
This was added and reverted.
https://github.com/code-ready/snc/pull/338 then https://github.com/code-ready/snc/pull/373

It would be good to have this done at some point.

**Comment by praveenkumar** [comment]
@guillaumerose So now openshift by default uses `single-node-developer` annotation which kind of much better than `single-node-cluster` profile since this annotation is identified by all the operators to make the decision about cluster type and provision the cluster like not having mutiple replica.

```json
 $ oc get deployment console-operator -n openshift-console-operator -ojsonpath='{.metadata.annotations}' | jq .
{
  "config.openshift.io/inject-proxy": "console-operator",
  "deployment.kubernetes.io/revision": "2",
  "include.release.openshift.io/self-managed-high-availability": "true",
  "include.release.openshift.io/single-node-developer": "true"
}
```

I think we can now close this.
