### ISSUE TITLE
Be able to change the subnet used for communicating with the VM

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1697]
The subnet chosen for the userland network stack is arbitrary and might collide with the local network. User should be able to change it.

**Comment by gbraad** [comment]
The problem is that part of this is dictated by the VMN itself on startup.
For Hyper-V it is possible to use the kvp messaging to pass this on startup, but no such thing on the other platforms (libvirt could, but never tried)

the other would be to use a link-local address assignmment, and do NOT use the actual assignment in a 192.168. or 172. segment, but use 169. etc or an IPv6 address instead

**Comment by guillaumerose** [comment]
Yes I know this is a problem for current network mode. With vsock, it's far more easier.

**Comment by cfergeau** [comment]
I'd be inclined to close this until we get more reports of subnet collisions
