### ISSUE TITLE
Custom CAs installed on the host not included in the VM

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1728]
If I install a custom CA on my machine, then launch crc. The CA will not be present in VM and therefore I won't be able to connect to remote services "securely". 

This can be a cause of https://github.com/code-ready/crc/issues/1675#issuecomment-734500085

**Comment by cfergeau** [comment]
Imo this is not crc's job to add these CAs if we want to stay as close as possible to what is needed on a real cluster. We can point in our docs at the OpenShift doc describing how to do it if this becomes a common issue.

**Comment by guillaumerose** [comment]
Docker Desktop and minikube do it. https://minikube.sigs.k8s.io/docs/handbook/untrusted_certs/

**Comment by gbraad** [comment]
There is an openshift way. We should NOT create a specific CRC way to solve this; we did with Minishift and this competed and caused issues with expectations for CRC.

The problem is that the containers are inherited fromm the initial set that was given IIRC, so this means a 'restart' is needed. So, let's look at the described way and refer our documentation to this instead.

**Comment by gbraad** [comment]
https://docs.openshift.com/container-platform/4.6/builds/setting-up-trusted-ca.html

**Comment by cfergeau** [comment]
With 4.8 and the MCO enabled, the instructions from the OpenShift documentation should work out of the box, so I'd suggest closing this issue.
