### ISSUE TITLE
Add single toggle for preflight checks

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#1796]
Have a single toggle for preflight checks to disable with single config set

**Comment by gbraad** [comment]
This is to allow simplification of the config window (and startup)

**Comment by cfergeau** [comment]
I read the issues/PRs linked here, but it's not really clear why we want a global "disable all" config option. It "makes the UI simpler", but I could not find a description of what was wrong in  the UI. Sounds like we should also make the cmdline UI simpler, and remove all the individual skip-*/warn-* ?

**Comment by anjannath** [comment]
> I read the issues/PRs linked here, but it's not really clear why we want a global "disable all" config option. It "makes the UI simpler", but I could not find a description of what was wrong in the UI.

The UI was a bit complicated because preflight checks were shown as a drop down menu that had `skip check`, `show warning` and `unset` options, and it was suggested instead of a drop-down to use a checkbox, which would only offer a simple click to toggle between `skip` or `run` the checks as getting an warning is only used for debugging, and that led to the idea of having an option to skip all the checks, to allow a user who doesn't want to know about what all the different preflight checks and want to speed up the start process. or avoid an error from some check..

> Sounds like we should also make the cmdline UI simpler, and remove all the individual skip-_/warn-_ ?

i think the individual `skip-*` are useful, `warn-*` could be removed as they are only useful for debugging purposes

**Comment by cfergeau** [comment]
> that led to the idea of having an option to skip all the checks, to allow a user who doesn't want to know about what all the different preflight checks and want to speed up the start process. or avoid an error from some check..

Imo we should only show a subset of the skip options, the only ones which we know some people have to use. The other ones are mostly for debugging purpose, people who really want them can fallback to the command line. I don't consider disabling preflights to be an acceptable way of speeding up the start process.

> i think the individual skip-* are useful

As a user, why should I bother about the individual `skip-*` checks? I get the job done much faster by using this handy `disable-all` config switch, no need to understand each of them separately.

**Comment by anjannath** [comment]
Closing, we decided to de-clutter the tray UI by only putting configs that would be useful to the user (e.g `skip-admin-check` in case of windows) when there are less number of configs to skip a `skip-all` is not needed

**Comment by gbraad** [comment]
`warn` toggles have been removed in another PR
