### ISSUE TITLE
Authorization Server fail every couple of minutes and recovers after a minute

### ISSUE THREAD

**Issue by rezanirumand** [code-ready/crc#1807]
Every couple of minutes fresh installation of CRC fails with following error and recovers itself after 1~ minute. 

[crc.log](https://github.com/code-ready/crc/files/5753409/crc.log)

{
"error": "server_error",
"error_description": "The authorization server encountered an unexpected condition that prevented it from fulfilling the request.",
"state": "f722413a"
}

Additional Configuration:

I am using instruction provided on [Setting up CodeReady Containers on a remote server](https://access.redhat.com/documentation/en-us/red_hat_codeready_containers/1.20/html/getting_started_guide/networking_gsg#setting-up-remote-server_gsg)

Also i have added the cluster certificates to the root certificate authorities.
![certificates](https://user-images.githubusercontent.com/45873100/103337656-4e994600-4a7c-11eb-94cd-6cf637413401.PNG)

**Comment by praveenkumar** [comment]
@rezanirumand Is it happen only once just after a start or you are experiencing it multiple time?

**Comment by rezanirumand** [comment]
Hi @praveenkumar, Thanks for quikck reply.  I was not sure which pod you meant, so I attached all the related logs. 



[router-default-dcbbb64b9-rv6hv.txt](https://github.com/code-ready/crc/files/5753693/router-default-dcbbb64b9-rv6hv.txt)
[authentication-operator-7496b88c8b-h7zgq.txt](https://github.com/code-ready/crc/files/5753694/authentication-operator-7496b88c8b-h7zgq.txt)
[oauth-openshift-6fdd9bfd8d-n4blf.txt](https://github.com/code-ready/crc/files/5753695/oauth-openshift-6fdd9bfd8d-n4blf.txt)
[oauth-openshift-6fdd9bfd8d-p4k6d.txt](https://github.com/code-ready/crc/files/5753696/oauth-openshift-6fdd9bfd8d-p4k6d.txt)

**Comment by praveenkumar** [comment]
@rezanirumand Thanks for sharing the logs, going through the logs looks like `auth-operator` get error when the api server is not able to handle any request, it might be apiserver is reconcile, what kind of app are you deploying on this cluster, also since you are deploying it on remote server, also check the ha-proxy configs (https://github.com/code-ready/crc/pull/1797) .

```
E1230 08:53:12.833728       1 base_controller.go:250] "MangeOAuthAPIController" controller failed to sync "key", err: OAuth API servers are not ready. APIService check reporeted "oauth.openshift.io.v1" is not ready: 503 (the server is currently unable to handle the request)
```

oauth pods fail because the operator is not able to serve request.
```
internal error: the server is currently unable to handle the request (get oauthclients.oauth.openshift.io console)
```

**Comment by nirumand** [comment]
@praveenkumar Thanks for the analysis. I was tried diffrent ways to deploy an application, such as from source directly or using odo tool. The issue happens after i try to build an application.

I do not understand why an auth pod fails when there is a problem with an external proxy. If the request is failed due to haproxy timeout, then it should be just the request that is failed.

**Comment by cfergeau** [comment]
Could you try giving more memory to your crc instance in case the instability comes from memory pressure?

**Comment by nirumand** [comment]
Hi @cfergeau , i did try with 10GB but any more would be a problem for my hardware.

**Comment by vyom-soft** [comment]
Hi,
I am also facing the same issue. I have 32 GB.
I am on 1.22.0

**Comment by gbraad** [comment]
can you also provide some details about the setup itself?

**Comment by jerolimov** [comment]
I had the same issue since multiple versions and have this now again with the latest CRC 1.25.0.

My setup use 24 of 64 GB ram for the CRC installation:

```
crc config view
- consent-telemetry                     : no
- disk-size                             : 400
- memory                                : 24576
```

The issue happen right after installation (`crc setup && crc start`), after installing the Pipelines Operator and running 2 builds (1 BuildConfig and 1 Pipeline). The access from the browser fails (`crc console`) as well as internal communication. The BuildConfig Build fails for example with this error message:

```
Registry server Address: 
Registry server User Name: serviceaccount
Registry server Email: serviceaccount@example.org
Registry server Password: <<non-empty>>
error: build error: Failed to push image: error copying la... unauthorized: unable to validate token: ServiceUnavailable
```

For me this happen also very frequently. I stopped and started the cluster but it did not fixed the issue. I expect that esp. when starting a new cluster and installing some operators, there happen many requests in the backend to fetch additional resources, images, etc.

The console redirects me the the login form.

oc says:

```
# oc login and get pods works before, and then...

oc get pods
error: You must be logged in to the server (Unauthorized)

oc login -u kubeadmin -p K62b9-vc4yz-77Rvj-Jyhmo --insecure-skip-tls-verify=true https://api.crc.testing:6443
Error from server (InternalError): Internal error occurred: unexpected response: 400
```

**Comment by dhladky** [comment]
Same issue on version 1.28.0+08de64bd:

> crc status
CRC VM:          Running
OpenShift:       Unreachable (v4.7.13)
Disk Usage:      0B of 0B (Inside the CRC VM)
Cache Usage:     11.21GB
Cache Directory: /Users/dhladky/.crc/cache

**Comment by cfergeau** [comment]
Exactly the same issue with the authentication being unreachable? Or is your issue just `OpenShift: Unreachable` for now?
Can you provide more details about your setup?

**Comment by dhladky** [comment]
I am running CRC on Mac (Big Sur 11.5.1). 16 GB RAM.  The whole instance becomes unreachable. It looks like it overloads and then it recovers. crc status does this over time: 

dhladky@MacBook-Pro content-gateway % crc status
CRC VM:          Running
OpenShift:       Unreachable (v4.7.13)
Disk Usage:      26.34GB of 32.74GB (Inside the CRC VM)
Cache Usage:     11.21GB
Cache Directory: /Users/dhladky/.crc/cache
dhladky@MacBook-Pro content-gateway % crc status
CRC VM:          Running
OpenShift:       Starting (v4.7.13)
Disk Usage:      27.81GB of 32.74GB (Inside the CRC VM)
Cache Usage:     11.21GB
Cache Directory: /Users/dhladky/.crc/cache
dhladky@MacBook-Pro content-gateway % crc status 
CRC VM:          Running
OpenShift:       Running (v4.7.13)
Disk Usage:      22.75GB of 32.74GB (Inside the CRC VM)
Cache Usage:     11.21GB
Cache Directory: /Users/dhladky/.crc/cache

Similar sequence repeats. In the unreachable status first the error described above appears, then the whole pages do not load at all. During "starting" the web browser opens a pages, that says there are no applications deployed and after a while the Openshift web interface re-appears. I need re-login, but not always. Then it goes down and the process repeats.

**Comment by zzzeek** [comment]
Ive been suffering from this as well for some months on one lab machine, reinstalling the whole cluster etc. not really helping.   am starting to look into it more earnestly now.
