### ISSUE TITLE
Cannot run `oc login` when running in vsock mode and using Docker Desktop with Kubernetes activated

### ISSUE THREAD

**Issue by guillaumerose** [code-ready/crc#1838]
### General information

  * OS: macOS / Windows

### Steps to reproduce

  1. Start Docker Desktop
  2. Activate Kubernetes
  3. Start CRC with vsock mode
  4. Try oc login

### Description

Both apiserver of Kubernetes in Docker Desktop and authentication server of OpenShift in CRC are using the same port 127.0.0.1:6443.

OpenShift web console works because it uses port 443 (https://oauth-openshift.apps-crc.testing/login/htpasswd_provider), but the CLI uses the other port.

First, we can detect this issue by checking the port is free before starting the daemon and/or doing crc start.
We can also change the port of the authentication server. kube-apiserver is not configurable in Docker Desktop.

**Comment by cfergeau** [comment]
If you deploy an application in Docker Desktop k8s which uses port 443, will it also try to open it on localhost? This issue is about port 6443 / Docker desktop, but since vsock is using a shared host resource (port number allocation), we're bound to be having conflicts here and there. Hopefully it won't happen too much, but I think we won't know before it's more widely used.
