### ISSUE TITLE
Version info on "Red Hat CodeReady Containers" page

### ISSUE THREAD

**Issue by langdon** [code-ready/crc#1952]
On the "Sandbox" tab of https://cloud.redhat.com/openshift/create, you can download/install crc. However, it would be really nice if somewhere on that page it indicated what version of crc or openshift it provides. As I have to manually update, it would be nice if I could easily glance at this page (or even click the download link) and have some idea what version I would be getting before downloading and extracting it.

**Comment by praveenkumar** [comment]
This is what mostly be sync with what other options are offer even https://cloud.redhat.com/openshift/install/aws/installer-provisioned one if you check doesn't provide the version of which openshift you are going to installer just provide installer without any version info otherwise it will need to updated every single time when a new version available. We do maintain http://mirror.openshift.com/pub/openshift-v4/clients/crc/latest/release-info.json but is not directly consumable on cloud.redhat.com  :( . Also as soon as you click on `Get Started` it takes you to latest release doc which have version info and this is again what sync with other options.

**Comment by langdon** [comment]
However, the big difference between crc and the other options (at the moment at least) is that I need to manually check for updates and then manually update if a new version exists. As a result, it would be easier if I could just check a place on the web for "need to update" rather than downloading and extracting a 2.5G file. Perhaps just a new function in crc like "crc available-update" would be sufficient.

**Comment by praveenkumar** [comment]
> However, the big difference between crc and the other options (at the moment at least) is that I need to manually check for updates and then manually update if a new version exists. As a result, it would be easier if I could just check a place on the web for "need to update" rather than downloading and extracting a 2.5G file. Perhaps just a new function in crc like "crc available-update" would be sufficient.

@langdon As part of `crc start` we do display if a new version is available or not. You like to have a dedicated command for it?

**Comment by gbraad** [comment]
We do not own/control the content of the landing page :-/

We request this update need? Also, we do not have a mechanism in place for automatic updates. This would mean that an in-place update is going to be performed? More info about this might be helpful to decide on what to do.

**Comment by langdon** [comment]
probably the right answer was #1968 anyway :)
