### ISSUE TITLE
Include crc version info in the tray

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#2143]
It would be great to know the which crc version tray is using so we can use this info to create document link as per version instead pointing to latest one.

Also on the doc side it is only `x.y` not the patch version included.

**Comment by gbraad** [comment]
current version information is based on the 'version' command.

**Comment by anjannath** [comment]
the daemon contains a version endpoint `/api/version` from the HTTP API and `{"command":"version"}` using the binary protocol

We also show the version of crc in the tray's About window, but the documentation link points to the latest one, since that is a hardcoded link :( 

Windows eg.
![image](https://user-images.githubusercontent.com/8885742/112353329-a64cf380-8cf1-11eb-9a4c-a5294bacd78a.png)

**Comment by gbraad** [comment]
the reason why we brought this up is that the documentation link might not have to rely on the API to be active...
for instance, we extract version information from the binary when possible, We need to consider how to at least refer to the correct documentation, as we might also want to actually point to the release notes and known issues that are specific to the version used as `x.y.z`. Current documentation links do not allow this.
