### ISSUE TITLE
CRC/OCP Cert Expiration 

### ISSUE THREAD

**Issue by matgeb83** [code-ready/crc#2230]
From the CRC documentation, it is not clear if CRC/OCP will be operating or not after the original cert expires in 30 days.  if that is the case, do we have to delete and rebuild after 30 days?

**Comment by cfergeau** [comment]
I assume you are referring to https://code-ready.github.io/crc/#troubleshooting-expired-certificates_gsg ?
The correct statement is this one:
> Starting from CodeReady Containers 1.2.0, the embedded certificates can be automatically renewed by crc. The crc start command triggers the certificate renewal process when needed. Certificate renewal can add up to five minutes to the start time of the cluster.

Regarding the statement below, I don't remember why it was added, but it should be removed.
> As of the CodeReady Containers 1.10.0 release, the certificate renewal process is not working as intended. Follow this procedure to avoid potential errors due to certificate expiration.

We can reword this section of the documentation a little bit to make it clearer what the nominal case is, and what is a workaround if the code were to fail.

**Comment by matgeb83** [comment]
yes! that is right.  so you are saying that the expired certs should have no impact on an operational CRC? meaning CRC and OCP should operate fine with regretless of the expired certs. Ideally, CRC should continue to operate since rebuilding from scratch after doing alot of development and testing on it will not be feasible.

**Comment by cfergeau** [comment]
Relatively recent crc versions (I think I tried 1.18 or 1.17 recently) are able to renew their certs automatically. If the openshift cluster is running regularly, cert expiration should not be an issue. It's when you run `crc delete && crc start` that you'll notice expired certificates. When crc detects expired certificates, it is able to renew them, but it takes several minutes. Since you seem to be  keeping a long-lived environment I don't expect you use `crc delete` often, so you should not notice this.

**Comment by matgeb83** [comment]
This answers my questions.  Thank you @cfergeau  for the quick response.
