### ISSUE TITLE
[BUG] Followup of https://github.com/code-ready/crc/issues/2220

### ISSUE THREAD

**Issue by VivekBuzruk** [code-ready/crc#2511]
### General information

  * OS: Linux / macOS / Windows - CentOS Linux release 7.9.2009
  * Hypervisor: KVM / Hyper-V / hyperkit - KVM
  * Did you run `crc setup` before starting it (Yes/No)? Yes
  * Running CRC on: Laptop / Baremetal-Server / VM - Physical Machine (Intel® Core™ i5-4440S CPU @ 2.80GHz × 4, OS 64, memory 32GB)

## CRC version 
```bash
# Put `crc version` output here
CodeReady Containers version: 1.28.0+08de64bd
OpenShift version: 4.7.13 (embedded in executable)
```
  
## CRC status
```bash
# Put `crc status --log-level debug` output here
DEBU CodeReady Containers version: 1.28.0+08de64bd 
DEBU OpenShift version: 4.7.13 (embedded in executable) 
DEBU Running 'crc status'                         
DEBU Checking file: /home/XXXX/.crc/machines/crc/.crc-exist 
DEBU Checking file: /home/XXXX/.crc/machines/crc/.crc-exist 
DEBU Found binary path at /home/XXXX/.crc/bin/crc-driver-libvirt 
DEBU Launching plugin server for driver libvirt   
DEBU Plugin server listening at address 127.0.0.1:46203 
DEBU () Calling .GetVersion                       
DEBU Using API Version 1                          
DEBU () Calling .SetConfigRaw                     
DEBU () Calling .GetMachineName                   
DEBU (crc) Calling .GetState                      
DEBU (crc) DBG | time="2021-07-01T19:16:16+05:30" level=debug msg="Getting current state..." 
DEBU (crc) DBG | time="2021-07-01T19:16:16+05:30" level=debug msg="Fetching VM..." 
DEBU (crc) Calling .GetBundleName                 
DEBU (crc) Calling .GetIP                         
DEBU (crc) DBG | time="2021-07-01T19:16:16+05:30" level=debug msg="GetIP called for crc" 
DEBU (crc) DBG | time="2021-07-01T19:16:16+05:30" level=debug msg="Getting current state..." 
DEBU (crc) DBG | time="2021-07-01T19:16:16+05:30" level=debug msg="IP address: 192.168.130.11" 
DEBU Running SSH command: df -B1 --output=size,used,target /sysroot | tail -1 
DEBU Using ssh private keys: [/home/XXXX/.crc/machines/crc/id_ecdsa /home/XXXX/.crc/cache/crc_libvirt_4.7.13/id_ecdsa_crc] 
DEBU SSH command results: err: <nil>, output: 32737570816 12351578112 /sysroot 
DEBU Making call to close driver server           
DEBU (crc) Calling .Close                         
DEBU Successfully made call to close driver server 
DEBU Making call to close connection to plugin binary 
CRC VM:          Running
OpenShift:       Running (v4.7.13)
Disk Usage:      12.35GB of 32.74GB (Inside the CRC VM)
Cache Usage:     13.58GB
Cache Directory: /home/XXXX/.crc/cache
```

## CRC config
```bash
# Put `crc config view` output here
- consent-telemetry                     : no
- memory                                : 10240
- pull-secret-file                      : /mnt/YYYY/dtools/pull-secret.txt

```

## Host Operating System
```bash
# Put the output of `cat /etc/os-release` in case of Linux
# put the output of `sw_vers` in case of Mac
# Put the output of `systeminfo` in case of Windows
NAME="CentOS Linux"
VERSION="7 (Core)"
ID="centos"
ID_LIKE="rhel fedora"
VERSION_ID="7"
PRETTY_NAME="CentOS Linux 7 (Core)"
ANSI_COLOR="0;31"
CPE_NAME="cpe:/o:centos:centos:7"
HOME_URL="https://www.centos.org/"
BUG_REPORT_URL="https://bugs.centos.org/"

CENTOS_MANTISBT_PROJECT="CentOS-7"
CENTOS_MANTISBT_PROJECT_VERSION="7"
REDHAT_SUPPORT_PRODUCT="centos"
REDHAT_SUPPORT_PRODUCT_VERSION="7"

```

### Steps to reproduce

  1. crc start -n 8.8.8.8
  2. crc start -n 8.8.8.8 --log-level debug 
  3. 
  4. 

### Expected
To complete

### Actual
```
level=info msg="Waiting for kube-apiserver availability... [takes around 2min]"
Error waiting for apiserver: Temporary error: ssh command error:
command : timeout 5s oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 1\n (x9)
Temporary error: ssh command error:
command : timeout 5s oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 124\n (x36)
```

### Logs

Before gather the logs try following if that fix your issue
```bash
$ crc delete -f
$ crc cleanup
$ crc setup
$ crc start --log-level debug
```
Find attached both "log-level debug" output and sudo journalctl -u kubelet

[crc_start_log_level_debug.log](https://github.com/code-ready/crc/files/6748657/crc_start_log_level_debug.log)

[journalctl.log](https://github.com/code-ready/crc/files/6748634/journalctl.log)

**Comment by gbraad** [comment]
How long did you wait? 

---

```
level=debug msg="error: Temporary error: ssh command error:\ncommand : timeout 5s oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig\nerr     : Process exited with status 124\\n - sleeping 1s"
level=debug msg="RetryAfter timeout after 47 tries"
level=debug msg="Making call to close driver server"
level=debug msg="(crc) Calling .Close"
level=debug msg="(crc) DBG | time=\"2021-07-01T18:32:02+05:30\" level=debug msg=\"Closing plugin on server side\""
level=debug msg="Successfully made call to close driver server"
level=debug msg="Making call to close connection to plugin binary"
level=debug msg="Making call to close driver server"
level=debug msg="(crc) Calling .Close"
level=debug msg="(crc) DBG | time=\"2021-07-01T18:32:02+05:30\" level=debug msg=\"Closing plugin on server side\""
level=debug msg="Successfully made call to close driver server"
level=debug msg="Making call to close connection to plugin binary"
level=error msg="sending request - Post \"https://api.segment.io/v1/batch\": context deadline exceeded (Client.Timeout exceeded while awaiting headers)"
level=error msg="2 messages dropped because they failed to be sent and the client was closed"
Error waiting for apiserver: Temporary error: ssh command error:
command : timeout 5s oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 1\n (x10)
Temporary error: ssh command error:
command : timeout 5s oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 124\n (x37)
```

**Comment by VivekBuzruk** [comment]
Not sure about your question. I did not interrupt the command, it just exited with error.

**Comment by praveenkumar** [comment]
@VivekBuzruk  From #2220 journalctl logs look like kubelet was crashing for the user but eventually it works and reporter not able to reproduce it. Journal logs which you shared doesn't see any crash reports from kubelet side so may be something else.

**Comment by VivekBuzruk** [comment]
I said partially working as-> 
-- "crc start" terminate sometimes after "Waiting for kube-apiserver availability... [takes around 2min]" Not sure whether i need to follow above "stop-delete-setup-start" cycle every time (loosing my earlier work) I switch of my machine and restart next day.

  - Well such termination takes place, when I execute "oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig", the command takes some times but returns correct result. BUT,
  - Builds for most sample apps fail with an error - "error":"server_error","error_description":"The authorization server encountered an unexpected condition that prevented it from fulfilling the request.","state":"7bbf7767"

In brief, still waiting for good resolution of these issues. "crc start" finishes successfully after multiple trials (sometimes just 2). I am yet to find exact reason of failure but I suspect **"timeout"** for few commands as one reason and **"race conditions"**as another.

**Comment by cfergeau** [comment]
There has been several reports of such issues with rhel7.9/centos7.9 and OpenShift 4.7, but unclear what would be causing them :-/ Are you also experiencing this with more recent releases based on OpenShift 4.8?

**Comment by VivekBuzruk** [comment]
Yes, there are still issues.

After multiple attempts of "crc start ... / crc delete ..." (debug / non-debug) cycles at last I could successfully install crc-linux-1.32.1-amd64.

Once it flagged off saying installation is successful, but operator hub was empty. 

My findings are,
1] In some cases, crc does not even create /opt/kubeconfig file and even then it proceeds for next stage.
2] In certain cases, it appears to be issue related to timeout (ssh command and even oc commands).

In brief, there are either race conditions or in-appropriate privilege settings or timeouts based sequencing which are probably the cause.

Btw. There is another problem once it starts, in some cases it just logs out or raises authentication error (may be due to insufficient resources ....)

**Comment by adithyagk** [comment]
Hi ,
Was anyone able to get  a solution to this, been trying this since morning with no luck.
`[adithya@localhost ~]$ crc start
INFO Checking if running as non-root              
INFO Checking if running inside WSL2              
INFO Checking if crc-admin-helper executable is cached 
INFO Checking for obsolete admin-helper executable 
INFO Checking if running on a supported CPU architecture 
INFO Checking minimum RAM requirements            
INFO Checking if crc executable symlink exists    
INFO Checking if Virtualization is enabled        
INFO Checking if KVM is enabled                   
INFO Checking if libvirt is installed             
INFO Checking if user is part of libvirt group    
INFO Checking if active user/process is currently part of the libvirt group 
INFO Checking if libvirt daemon is running        
INFO Checking if a supported libvirt version is installed 
INFO Checking if crc-driver-libvirt is installed  
INFO Checking if systemd-networkd is running      
INFO Checking if NetworkManager is installed      
INFO Checking if NetworkManager service is running 
INFO Checking if /etc/NetworkManager/conf.d/crc-nm-dnsmasq.conf exists 
INFO Checking if /etc/NetworkManager/dnsmasq.d/crc.conf exists 
INFO Checking if libvirt 'crc' network is available 
INFO Checking if libvirt 'crc' network is active  
INFO Loading bundle: crc_libvirt_4.9.8...         
INFO Creating CodeReady Containers VM for OpenShift 4.9.8... 
INFO Generating new SSH Key pair...               
INFO Generating new password for the kubeadmin user 
INFO Starting CodeReady Containers VM for OpenShift 4.9.8... 
INFO CodeReady Containers instance is running with IP 192.168.130.11 
INFO CodeReady Containers VM is running           
INFO Updating authorized keys...                  
INFO Check internal and public DNS query...       
INFO Check DNS query from host...                 
INFO Verifying validity of the kubelet certificates... 
INFO Starting OpenShift kubelet service           
INFO Waiting for kube-apiserver availability... [takes around 2min] 
Failed to update cluster pull secret: Temporary error: ssh command error:
command : timeout 5s oc get secret --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 124
 (x13)
`
