### ISSUE TITLE
Feature: support GPU resources in CRC

### ISSUE THREAD

**Issue by erikerlandson** [code-ready/crc#2714]
As a data scientist, I would like to be able to install a CRC openshift cluster onto my machine, and also be able to configure my CRC cluster with support for using my local GPU.

**Comment by elmiko** [comment]
i think this would be a really cool feature to help enable the data science community, i have a feeling it might a little difficult because the GPU will need to be shared inside the CRC VM and then OpenShift would need to be able to build the GPU specific drivers inside the cluster(not sure if CRC allows build entitlements). perhaps on an OKD CRC it could build without the entitlements.

**Comment by mattpielm** [comment]
Definitely interesting. I looked at this some recently, and I think Linux/KVM is the only Hypervisor I found that does GPU pass-thru and CRC would use, but I may have missed something.

**Comment by erikerlandson** [comment]
cc @burrsutter

**Comment by gbraad** [comment]
This is not something we are pursuing; though you can contribute these parts. CRC is focusing on a developer story and we have very limited bandwidth to work on this.

Try to enable this first for OKD, and see what is necessary for the image: https://github.com/code-ready/snc/

**Comment by gbraad** [comment]
Anybody is free to experiment and propose an improvement. Even if only
aimed at Linux/KVM

**Comment by jsliacan** [comment]
Seems that there is a user story behind the original suggestion. Let's see if anyone picks this up before it goes stale again.
