### ISSUE TITLE
RFE: rename CRC to minishift

### ISSUE THREAD

**Issue by ktdreyer** [code-ready/crc#284]
The phrase "CodeReady Containers" does not make it immediately obvious to me that this is a small OpenShift environment for a laptop.

The phrase "minishift" makes it obvious that this is a small OpenShift experience. It also matches "minikube", which has a large developer mindshare upstream.

Can we rename the "CodeReady Containers" project to "minishift"?

**Comment by gbraad** [comment]
Minishift is a different project and aims at 3.11 only. We purposely moved away from Minishift to indicate the breakage and also to show this is not a fork of minikube/minishift. There might be a better namingoption possible, but it will not be minishift.

**Comment by LalatenduMohanty** [comment]
The current project architecture CRC is no way similar to Minishift (as @gbraad  mentioned) and there is no way to boot OKD in CRC (because of OpenShift 4.0) at this  point. Where as in Minishift `OKD` was default. Also in CRC we can not promise similar feature set as Minishift because of changes in OpenShift 4.0. So `minishift` and `CRC` are very different projects.

**Comment by ktdreyer** [comment]
Thanks for considering this and responding.

I think it is fine that CRC has a radically different architecture. In fact OpenShift 2 was radically different than OpenShift 3. In terms of feature comparisons, OpenShift 4.0 dropped many features compared to OpenShift 3.11. I think it's just the nature of the landscape here. It's ok if minishift and CRC are different under the hood, or even have different features and user experience.

The reason I opened this ticket is that you have struck gold with the "minishift" name. This is really valuable marketing for your project, and I think it would help CRC to adopt a name that is stickier for developers.

When I ask OpenShift solutions architects "what is the replacement for minishift", they say "CRC". This is happening in many user conversations. When the discussions are that high-level, it makes sense to me to keep the minishift name.

When I look around at the various projects that developers are building for Kubernetes, even developers are going with Minikube in their CI systems because it has the mindshare. You can preserve that by naming this project "minishift".

**Comment by gbraad** [comment]
> "what is the replacement for minishift", they say "CRC"

And this is why this decision was made, as it moves away from the expectations that minishift gave.

Minishift was lightweight and followed a similar deployment strategy by deploying the environment, while we using an image-based approach that is identical to an actual OpenShift cluster. minikube and minishift made decisions that made them non-production like... and this is not what CRC is, it is the same result and not minimized if you understand what I mean ;-)

**Comment by alekonko** [comment]
Also in my opinion the name is not explanatory of what the product does, and I also know that it is right to give the names you like best.
More than anything else can confuse ideas with another product of Redhat, Codeready Workspaces (formerly Eclipse-Che)
I understand that minishift does something else or anyway is based on the 3.x version, but I don't make sense anymore to not confuse too much to choose a name that is more explicit?

Anyway thanks for the contribution !! :D

Greetings

Alessandro

**Comment by gbraad** [comment]
> the name is not explanatory of what the product does,

CRC is meant to assist in the process of developing container-based applications for deployment on OpneShift as a platform. This is also the first use-case we try to solve by seting up a full OpenShift 4.x cluster that can run your application. However, over time we will also provide simpler functionality to just deal with running containers (and pods) without the use of OpenShift, like eg. targeting `podman` directly.

I am not sure how this conflicts with Workspaces, as this product has a different aim. Can you explain this a little bit more?

> to not confuse too much to choose a name that is more explicit?

I am afraid this boat has sailed. However I will express your concerns ...

**Comment by sspeiche** [comment]
Naming is hard and we went back and forth for some time. @gbraad has it right. We also had feedback that people were confused of all the options and when to use which for what purpose, so for OpenShift v4 we wanted to try to address that and make it clear it is something similar and different.

Appreciate the feedback on the naming, we've heard this and we had the discussion again. Though at this point we are looking just to move forward and hopefully this is just a point in time statement. The upstream even has a large number of options now beyond minikube so aligning with that naming may not hold up longer term and also is misleading since it really isn't based on that.

**Comment by cfergeau** [comment]
I don't think we need to keep this open after Steve's statement.
