### ISSUE TITLE
Investigate what is needed to allow switching between presets without a delete

### ISSUE THREAD

**Issue by gbraad** [code-ready/crc#2942]
... this means the preset files remain on the disk to allow a 'quicker' switch (and preserving 'state').

**Comment by praveenkumar** [comment]
Initial thought around this is to implement something like profile we used to had with minishift where each profile had different name with different VM. In case of preset we can have different name for different preset like for `OpenShift` preset it is `crc` and for podman it is `crc-podman` so the user can switch accordingly without delete the existing preset.

Initial work for this spike to understand the code refactor require for this and how user can switch to preset without deleting existing preset, we might need to stop the current preset so the resources are consumed properly or let user to do it so if they have enough resource to run both preset then we should allow it.

**Comment by cfergeau** [comment]
Or we could have `~/.crc/machines/podman`, `~/.crc/machines/openshift` and rename/symlink the one we want to use to `crc`. This might be less invasive than refactoring all the code to be able to use different values for `MachineInstanceDir`.

**Comment by praveenkumar** [comment]
In case of `podman machine` user can run a single VM since it is limitation on user network stack side where in the VM mac is hardcoded https://github.com/containers/gvisor-tap-vsock/blob/main/cmd/vm/main_linux.go#L40 and associated with the `192.168.127.2` IP on the VM. One way to look into this to refactor gvisor-tap-vsock and crc code to have mac defined as per preset and use it.

**Comment by cfergeau** [comment]
```
flag.StringVar(&mac, "mac", "5a:94:ef:e4:0c:ee", "mac address")
```
This defines a `--mac` command line flag with `5a:94:ef:e4:0c:ee` as the default value.
I think the mac can be changed by running gvisor-tap-vsock with something like this:
```
podman run gvisor-tap-vsock quay.io/crcont/gvisor-tap-vsock --mac ab:cd:ef:12:34:56
```
Should be fairly easy to change at bundle generation time if the goal is to have a different IP for each bundle.

**Comment by cfergeau** [comment]
The DHCP IP assignment is done in https://github.com/code-ready/crc/blob/6ff0170104e74acbee36d492969b3db1eb3eaf08/cmd/crc/cmd/daemon.go#L73-L75
There might be some issues with DNS though if both VMs run at thesame time, I'm not sure the podman bundle is not expecting to be able to use `crc.testing`.

I did not mean to imply it's easy/..., I was only replying to your comment to say that the mac address is not hardcoded in gvisor-tap-vsock, and that I don't think changes are needed in gvisor-tap-vsock for the mac address.

**Comment by praveenkumar** [comment]
So I worked on https://github.com/code-ready/crc/pull/2966 one initially using the logic https://github.com/code-ready/crc/issues/2942#issuecomment-1014295681 but in windows we don't able to perform symlink without elevated privileges or ask user to switch to dev mode (both are no-go in our case) https://github.com/golang/go/issues/22874.

Another logic which I thought is to copy instead of symlink only for windows but that  is also not working with current flow.
- start crc => Check if existing `machines/crc` folder exist and delete it, check if preset directory `machine/<preset>` exist and copy the content to crc directory.
- stop crc => stop the VM and copy the content of `machines/<preset>`

So now on windows when we run the VM with any preset then the disk of preset is associated with that VM and during the start again with a different/same preset it is not able to delete the disk because it is always in use.  

```
failed to Delete: remove C:\Users\anath\.crc\machines\crc\crc\Virtual Machines\49BF4DB3-E32E-42DC-ABDA-595699C13196.vmcx: The process cannot access the file because it is being used by another process.
```

What I think if we need to make this all work, this need to done ground up, like make required changes on the mac address https://github.com/code-ready/crc/issues/2942#issuecomment-1021178297 and then adding map to daemon and also try to find a way https://github.com/code-ready/crc/blob/master/pkg/crc/constants/constants.go#L13-L14 to aware it according to preset.
