### ISSUE TITLE
Expose both root/rootless socket

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#3019]
As of now we are only exposing the `/run/podman/podman.sock` which consumed by docker client or API side, we need to expose both the socket if someone wants to consume API in rootless mode.

**Comment by cfergeau** [comment]
For future reference, this is a follow-up of these commits which expose the podman socket as unix socket on the host, instead of having to access it through a ssh tunnel.
https://github.com/code-ready/crc/commit/d983719d34e7ca00adb1dc20290cd8453f7d2909
https://github.com/code-ready/crc/commit/790195bb3baafbb222c4f496575123fa367cdae8
