### ISSUE TITLE
Use `/etc/hosts` instead `/etc/resolv.conf` for OSX

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#314]
At this moment we are using the `/etc/resolv.conf` to add the nameserver as vm ip to resolve the cluster specific domain name. It is problematic since most of users have `/etc/resolv.conf` symlinked to `/var/run/resolv.conf` and that also change whenever network restart happen. `oc` also respect `/etc/hosts` entry so atleast we can have apiserver and auth URI as part of this.

**Comment by gbraad** [comment]
This issue is created as `oc` does not understand the macOS resolver when compiled without CGO; see https://github.com/openshift/origin/issues/23266#issuecomment-508390514

Note: It is not that `oc` respects `/etc/hosts` but gracefully falls back to libc resolving when the Go binary is not compiled using CGO. This is more of a side-effect than a choice.

**Comment by gbraad** [comment]
Ref: https://github.com/code-ready/crc/issues/293

**Comment by praveenkumar** [comment]
resolved by #315
