### ISSUE TITLE
[BUG] registry value for autostart not cleaned for windows

### ISSUE THREAD

**Issue by adrianriobo** [code-ready/crc#3147]
During the `crc cleanup` command it is expected any configuration on the system will be cleaned.

At the moment to control the autostart of the tray a registry value( `KEY_CURRENT_USER\SOFTWARE\Microsoft\Windows\CurrentVersion\Run\redhat.codereadycontainers.tray`) is added to the registry.

Then during the `crc cleanup` that value it is not deleted.

**Comment by praveenkumar** [comment]
This registry value is included as part of install so should it be part of uninstall script instead cleanup side? As of now `clean up` try to remove configurations which are part of setup. Also moving forward we are trying to go away with tray so this shouldn't be crc responsibility to check the registry changes which made by crc.

**Comment by anjannath** [comment]
> This registry value is included as part of install so should it be part of uninstall script instead cleanup side?

yes, this should be done from the msi during uninstall

**Comment by anjannath** [comment]
btw, since this way of  "autostarting" tray is configured from electron, in windows it creates a registry entry to do it, and in macOS it adds the app to `Login Items`, but there is no easy way to remove `Login Items` in macOS (as far as i've searched) you could use an `applescript` to automate the GUI interactions to remove it.
