### ISSUE TITLE
CodeReady-Container(CRC) Installation in Restricted Network/Local Network : How to do

### ISSUE THREAD

**Issue by biruand1016** [code-ready/crc#3344]
Hello
I am trying to install CRC 4.11.1 on CentOS 8 in restricted network/local network which has no internet.
Install environment is following
Host: 4 cores, 12GB RAM, 300GB HDD
Host OS : CentOS 8 Stream
Hypervisor : Libvirt/KVM
install tools : crc-2.8.0, crc_libvirt_4.11.1_amd64.crcbundle
Firstly, I downloaded crc-2.8.0, pull secret, and crc_libvirt_4.11.1 and copied it into the host which does not connect to internet.
Then, I performed below command in CLI of the host
$ crc setup -b /opt/crc_libvrit_4.11.1_amd64.crcbundle
$ crc start -p /opt/pull_secret.txt
I failed installationg.
while starting openshift cluster, I got error

Temporary error: ssh command error:
command : timeout 5s oc get nodes --context admin --cluster crc --kubeconfig /opt/kubeconfig
err     : Process exited with status 124

How to do for fixing this issue?
why does this error happen?
Can I install CRC 4.11.1 on CentOS 8 in restricted network?
If I can install, what do i do?, and what do i download?

**Comment by praveenkumar** [comment]
@biruand1016 please use issue template to create the issue so that we have all the required information around you setup like is the host a virtual machine (so nested setup) or on baremetal and debug logs.

- https://github.com/code-ready/crc/issues/new?assignees=&labels=kind%2Fbug%2C+status%2Fneed+triage&template=bug_report.md&title=%5BBUG%5D 

closing this one because it doesn't provide enough info around setup.
