### ISSUE TITLE
Projects stuck in "terminating"

### ISSUE THREAD

**Issue by wrichter** [code-ready/crc#355]
crc 0.89.0-alpha-4.1.6+8e9c40e / OSX / hyperkit

whenever I do an oc delete project, it remains stuck in "Terminating". Not sure if it is the same as #268

**Comment by praveenkumar** [comment]
@wrichter I tested it by creating a project after the `crc start` on hyperkit and then able to delete without any issue.

```
$ oc new-project foobar
Now using project "foobar" on server "https://api.crc.testing:6443".

You can add applications to this project with the 'new-app' command. For example, try:

    oc new-app centos/ruby-25-centos7~https://github.com/sclorg/ruby-ex.git

to build a new example application in Ruby.

11:55 $ oc delete project foobar
project.project.openshift.io "foobar" deleted
```

It can occur because of CRD's [0][1] also, by any chance you are using some crd's which is not properly get cleaned ?

[0] kubernetes/kubernetes#60807
[1] kubernetes/kubernetes#60807 (comment)

**Comment by wrichter** [comment]
you are right, creating and deleting a project immediately works. Once I instantiate an operator, I can no longer clean up everything through oc delete project.

**Comment by praveenkumar** [comment]
@wrichter Thanks for confirmation, I am closing this issue since it is not part of crc.
