### ISSUE TITLE
Error: X509 cert signed by unknown authority

### ISSUE THREAD

**Issue by hupiper** [code-ready/crc#367]
With ./crc start using crc 0.89 alpha with libvirt 4.1.6 bundle: Error: unable to connect to the server: x509: certificate signed by unknown authority (possibly because of "crypto/verification error" while trying to verify candidate authority certificate "kube-apiserver-lb-signer")

**Comment by hupiper** [comment]
Just a follow-up: the cluster starts up, but api is not available for logging in, etc.

**Comment by hupiper** [comment]
I saw that I had old files in my .crc directory. Deleted the directory, deleted the vm, started over with setup, then start. Now getting an ssh error: 

ERRO Error occurred: ssh command error:
command : date --date="$(sudo openssl x509 -in /var/lib/kubelet/pki/kubelet-client-current.pem -noout -enddate | cut -d= -f 2)" --iso-8601=seconds
err     : exit status 255
output  :

When I do this in the VM, I get a valid response: 2019-08-19T06:54:11+00:00
Not sure why it's having trouble sshing into the VM.

**Comment by hupiper** [comment]
added -o UserKnownHostsFile=/dev/null to the ssh command I was using - it added the host to the knownhosts file and I got past the ssh error. I had deleted the old entry out of the known hosts file when I got the initial error above, and the process did not add the new host (VM) to my knownhosts file.

**Comment by hupiper** [comment]
The install completed correctly and I'm now aboe to log in. Someone needs to check the ssh setup to make sure it behaves correctly.

**Comment by praveenkumar** [comment]
@hupiper ssh error which you got is because there is delay, we already have a PR to overcome this error.

**Comment by hupiper** [comment]
I think it is more than a delay, but I can't find the PR you are referring to. Once I added the VM to my known hosts file it worked without a hitch. I also think there needs to be clean up if a previous version was installed.

**Comment by praveenkumar** [comment]
@hupiper I was referring to https://github.com/code-ready/crc/pull/363 one because https://github.com/code-ready/crc/blob/master/pkg/crc/cluster/cluster.go#L13-L14 is run by driver ssh command which already have `-o ConnectionAttempts=3 -o ConnectTimeout=10 -o ControlMaster=no -o ControlPath=none -o LogLevel=quiet -o PasswordAuthentication=no -o ServerAliveInterval=60 -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null core@192.168.130.11 -o IdentitiesOnly=yes` options as part of running the ssh command.

Can you try to build binary from the master and use it or have it from http://artifacts.ci.centos.org/minishift/crc/pr/363/

**Comment by jwendell** [comment]
I am getting this error as well, on latest released version (0.89) and on this version from https://github.com/code-ready/crc/pull/363 linked in the above comment.

Not sure if it's the same root cause, but since it shows the same error message, thought it would be good to comment here before opening a new issue.

The steps to reproduce are:
1. Start crc.
1. Run `export KUBECONFIG=$HOME/.crc/machines/crc/kubeconfig`
1. Everything is working fine as I am a cluster-admin
1. Create a regular (non-admin) user. I'm using [this script](https://github.com/jwendell/temp/blob/master/ocp-regular-users/user-creation.sh) to create two regular users.
1. Try to login as the regular user we just created:
```
$ oc login  --insecure-skip-tls-verify=true -u user1
error: x509: certificate signed by unknown authority
```
Verbose output:
```
$ oc --loglevel=8 login --insecure-skip-tls-verify=true -u user1
I0803 10:18:44.074696    8572 loader.go:359] Config loaded from file /home/jwendell/.crc/machines/crc/kubeconfig
I0803 10:18:44.075322    8572 loader.go:359] Config loaded from file /home/jwendell/.crc/machines/crc/kubeconfig
I0803 10:18:44.075612    8572 round_trippers.go:416] HEAD https://api.crc.testing:6443/
I0803 10:18:44.075621    8572 round_trippers.go:423] Request Headers:
I0803 10:18:44.080884    8572 round_trippers.go:441] Response Status: 403 Forbidden in 5 milliseconds
I0803 10:18:44.080895    8572 round_trippers.go:444] Response Headers:
I0803 10:18:44.080902    8572 round_trippers.go:447]     Cache-Control: no-store
I0803 10:18:44.080908    8572 round_trippers.go:447]     Content-Type: application/json
I0803 10:18:44.080913    8572 round_trippers.go:447]     X-Content-Type-Options: nosniff
I0803 10:18:44.080919    8572 round_trippers.go:447]     Content-Length: 186
I0803 10:18:44.080924    8572 round_trippers.go:447]     Date: Sat, 03 Aug 2019 14:18:44 GMT
I0803 10:18:44.080929    8572 round_trippers.go:447]     Audit-Id: e50d9928-0009-4140-bc5c-bd70599846da
I0803 10:18:44.081419    8572 round_trippers.go:416] GET https://api.crc.testing:6443/apis/user.openshift.io/v1/users/~
I0803 10:18:44.081430    8572 round_trippers.go:423] Request Headers:
I0803 10:18:44.081438    8572 round_trippers.go:426]     Accept: application/json, */*
I0803 10:18:44.081444    8572 round_trippers.go:426]     User-Agent: oc/v1.13.4+785687c (linux/amd64) kubernetes/785687c
I0803 10:18:44.088993    8572 round_trippers.go:441] Response Status: 200 OK in 7 milliseconds
I0803 10:18:44.089012    8572 round_trippers.go:444] Response Headers:
I0803 10:18:44.089017    8572 round_trippers.go:447]     Audit-Id: 96d5c14e-f721-40c7-8a82-1cd2bfb97893
I0803 10:18:44.089023    8572 round_trippers.go:447]     Cache-Control: no-store
I0803 10:18:44.089029    8572 round_trippers.go:447]     Cache-Control: no-store
I0803 10:18:44.089035    8572 round_trippers.go:447]     Content-Type: application/json
I0803 10:18:44.089041    8572 round_trippers.go:447]     Date: Sat, 03 Aug 2019 14:18:44 GMT
I0803 10:18:44.089045    8572 round_trippers.go:447]     Content-Length: 242
I0803 10:18:44.089065    8572 request.go:942] Response Body: {"kind":"User","apiVersion":"user.openshift.io/v1","metadata":{"name":"system:admin","selfLink":"/apis/user.openshift.io/v1/users/system%3Aadmin","creationTimestamp":null},"identities":null,"groups":["system:authenticated","system:masters"]}
I0803 10:18:44.089672    8572 request_token.go:87] GSSAPI Enabled
I0803 10:18:44.089708    8572 round_trippers.go:416] GET https://api.crc.testing:6443/.well-known/oauth-authorization-server
I0803 10:18:44.089714    8572 round_trippers.go:423] Request Headers:
I0803 10:18:44.089719    8572 round_trippers.go:426]     X-Csrf-Token: 1
I0803 10:18:44.090226    8572 round_trippers.go:441] Response Status: 200 OK in 0 milliseconds
I0803 10:18:44.090235    8572 round_trippers.go:444] Response Headers:
I0803 10:18:44.090239    8572 round_trippers.go:447]     Audit-Id: 518f1b70-36cd-40df-b157-f33f73e6b3ba
I0803 10:18:44.090242    8572 round_trippers.go:447]     Cache-Control: no-store
I0803 10:18:44.090245    8572 round_trippers.go:447]     Content-Type: application/json
I0803 10:18:44.090252    8572 round_trippers.go:447]     Content-Length: 573
I0803 10:18:44.090258    8572 round_trippers.go:447]     Date: Sat, 03 Aug 2019 14:18:44 GMT
I0803 10:18:44.090328    8572 round_trippers.go:416] HEAD https://oauth-openshift.apps-crc.testing
I0803 10:18:44.090336    8572 round_trippers.go:423] Request Headers:
I0803 10:18:44.112274    8572 round_trippers.go:441] Response Status:  in 21 milliseconds
I0803 10:18:44.112294    8572 round_trippers.go:444] Response Headers:
I0803 10:18:44.112300    8572 request_token.go:439] falling back to kubeconfig CA due to possible x509 error: x509: certificate signed by unknown authority
I0803 10:18:44.112349    8572 round_trippers.go:416] GET https://oauth-openshift.apps-crc.testing/oauth/authorize?client_id=openshift-challenging-client&code_challenge=DW8nLnM9G_H1zJLaMGtjCpUzytN_I_BQ1VN2KZtyWPE&code_challenge_method=S256&redirect_uri=https%3A%2F%2Foauth-openshift.apps-crc.testing%2Foauth%2Ftoken%2Fimplicit&response_type=code
I0803 10:18:44.112359    8572 round_trippers.go:423] Request Headers:
I0803 10:18:44.112367    8572 round_trippers.go:426]     X-Csrf-Token: 1
I0803 10:18:44.116070    8572 round_trippers.go:441] Response Status:  in 3 milliseconds
I0803 10:18:44.116098    8572 round_trippers.go:444] Response Headers:
F0803 10:18:44.116129    8572 helpers.go:116] error: x509: certificate signed by unknown authority
```

It's worth to mention that this workflow above works fine in a proper OCP4 (AWS) cluster.

**Comment by praveenkumar** [comment]
@jwendell your issue is complete different since you are trying to export `KUBECONFIG` yourself which is not advised for the users. Step-2 `Run export KUBECONFIG=$HOME/.crc/machines/crc/kubeconfig` shouldn't be done but instead login to `kube-admin` user as it shows at the end of the output when cluster creation is finish without any issue and then create another user and try to login.

1. Start crc.
2. Run `oc login -u kubeadmin -p <>  <api_endpoint>`   as shown in the successful run.
3. Everything is working fine as I am a cluster-admin
4. Create a regular (non-admin) user. I'm using this script to create two regular users.
5. Try to login as the regular user we just created:

**Comment by cfergeau** [comment]
Not really sure what this issue is about/what steps are needed to fix it. Should we close this?

**Comment by praveenkumar** [comment]
@jwendell Does your issue go away with the steps we mentioned, we are not advising user to use export `KUBECONFIG` file since this is for cluster `system:admin` role.

**Comment by jwendell** [comment]
> @jwendell Does your issue go away with the steps we mentioned, we are not advising user to use export `KUBECONFIG` file since this is for cluster `system:admin` role.

Yep, that worked, thanks.
