### ISSUE TITLE
Running make_build_docs on Mac machine fails with an error "Error: error creating libpod runtime: dial unix /run/podman/io.podman: connect: no such file or directory"

### ISSUE THREAD

**Issue by bryantson** [code-ready/crc#430]
Environment:
- MacOS Mojave 10.14

Running make_builddoc on MacMachine fails with the following error:

_"Error: error creating libpod runtime: dial unix /run/podman/io.podman: connect: no such file or directory"_

**Detailed response is shown below:**
podman run -v /Users/bryantson/Downloads/CHECTL/crc/docs:/docs:Z --rm registry.gitlab.com/gbraad/asciidoctor-centos:latest -b html5 -D /docs/build /docs/source/getting-started/master.adoc
Error: error creating libpod runtime: dial unix /run/podman/io.podman: connect: no such file or directory
make: *** [build_docs] Error 125

**Comment by anjannath** [comment]
the docs are built inside a container, and needs podman, in macOS you'll
need to use something like boot2podman, as there's no native podman support
for macOS.

How did you install podman on your machine?

with crc there's plan to support running podman, since you already have a
VM with podman running.

**Comment by gbraad** [comment]
Not an issue. we will however in future set up a podman machine to perform the doc builds in when not on Linux. For now, not on the roadmap due to time constraints.
