### ISSUE TITLE
Remove virtualbox as a supported driver from the linux platform

### ISSUE THREAD

**Issue by praveenkumar** [code-ready/crc#503]
We are not testing and have any kind of POC of a working crc using the virtualbox as `vm-driver`, better to remove it and warn use before hand.

**Comment by cfergeau** [comment]
Fixed by https://github.com/code-ready/crc/commit/6d4c87211c02107d1e6235dd6a2481f0e85c9257

**Comment by dmvolod** [comment]
Hi @praveenkumar 
Is there any chance to get get support virtualbox driver on linux for crc?
I could help with it if possible.
Thanks in advance.

**Comment by cfergeau** [comment]
> Hi @praveenkumar
> Is there any chance to get get support virtualbox driver on linux for crc?

What would be the use case/user story for that? (ie why would one have to use virtualbox on linux rather than libvirt/qemu/kvm?)

**Comment by gbraad** [comment]
> Is there any chance to get get support virtualbox driver on linux for crc?

Our tests have concluded that native virtualization is easier to deal with in settingup, we even automate this as much as possible, and they consume less resources. Mostly due to the fact they are tailored towards the host platform. However, VirtualBox on Windows and macOS as driver are provided for certain situation were policies prevent the user from self-admin, etc. Windows users for example are often confronted by the restriction that a virtualization suite has been chosen by the other tools they use or by the administrative team. This is less likely on Linux, so we have been opinionated to pursue a native solution. Although, we do not prevent people to add the needed drivers and support. We really do not have the resources and time on our schedule to handle more platforms and hypervisor combinations. We have learned from dealing with Minikube and Minishift and decided to not support these drivers from a basic installation. If people wanna use it, consider manual set up. We decided this as acceptable as long as we communicated the additional work was needed. In the case of Linux, nothing prevents outside contributors to add support. But note, 'supported' means more than just adding the setup and driver code, but also being able to run regular tests, integration ... And this is what we talk about here. (Note: Linux has never seen vbox support in our codebase, except for PoC purposes by scripts).

**Comment by tsmaeder** [comment]
@gbraad not supporting those cases is fine, but if you come to the crc doc through google (as people are wont to do), you don't see any disclaimer, VirtualBox is even mentioned in the doc.pdf that is in the Windows crc download. However, the instructions don't lead to a fully functional installation (see https://github.com/code-ready/crc/issues/313). That gives a bad experience to first time users ("gesehen, gelacht, gelöscht" as they say in German).

The problem on Windows is that you can't run Hyper-V and VirtualBox in parallel. So if you need VirtualBox for other things like running Fedora (as I do), you're screwed (even if you _do_ have admin on your box).
Also, you cannot use Hyper-V on a Windows Home machine.  Not saying this is a huge problem, but it might prevent some folks giving it a go on a home machine.

**Comment by gbraad** [comment]
This is understandable, and the 'disclaimer' note has been mentioned several times. Purposely we do not mention the VirtualBox option on the download page and only hint this from the documentation side the and the use of the `--vmdriver` option.

The start IS actually a working cluster, but you do not have DNS entries setup: #756 was created for this, as it would contain the same or similar entries as for macOS. however, the issue #757 might be able to resolve part of this. Although, most of the team members do not believe this is the way to go. So, we can only offer documentation and a disclaimer message.

**Comment by gbraad** [comment]
> The problem on Windows is that you can't run Hyper-V and VirtualBox in parallel. 

and this is why we took an opnionated stance and 'only' support the native hypervisors. Note: when WSL2 is enabled in upcoming releases, this will cause similar related issues as this relies on Hyper-V and renders the use of VirtualBox or VMware impossible.

**Comment by tsmaeder** [comment]
You know "opinionated" used to be an insult ;-)

**Comment by gbraad** [comment]
VirtualBox support has been deprecated, See #838
