### ISSUE TITLE
Documentation should mention 'htpasswd_provider' use for the web console

### ISSUE THREAD

**Issue by cfergeau** [code-ready/crc#679]
One needs to click on this before entering login/password, which can be confusing.

**Comment by cfergeau** [comment]
They don't mention it in OpenShift documentation https://docs.openshift.com/container-platform/4.1/web-console/web-console.html :(

**Comment by anjannath** [comment]
The name can be changed so we could just change it to something intuitive e.g `developer_login` instead of `htpasswd_provider`

**Comment by robin-owen** [comment]
Apologies, this issue was accidentally overlooked. Assigned myself and added it to the Documentation project.

Information about having to select `htpasswd_provider` to log in as the `developer` user will go in the "Accessing the OpenShift web console" section of the documentation.

This is currently "to do" until we have the `xref`s in the docs changed to `link[]` to avoid potential merge conflicts (I have a PR submitted for this at the moment, #1374).

**Comment by gbraad** [comment]
This was recently an issue and wanted to bring this up on the docs sync: https://github.com/code-ready/crc/issues/1371.

**Comment by robin-owen** [comment]
Fixed by #1392.
