### ISSUE TITLE
Lean crc executable

### ISSUE THREAD

**Issue by makuhama** [code-ready/crc#857]
The downloaded crc executable (v1.2) is 2168226726 bytes! I suspect it has quite a few artifacts inside needed for (and only for crc setup).

Please extend Makefile and add build instructions how to create a lean crc executable without these artifacts (obsolete after crc setup).

**Comment by cfergeau** [comment]
The default make target will create what you call a 'lean' executable. You need to use `make embed_bundle` to generate an executable similar to the one you download.

**Comment by gbraad** [comment]
Not sure about the question if you mean this for development or general distribution?

**Comment by makuhama** [comment]
@gbraad The reply by @cfergeau was totally sufficient (for me). I have intentionally not asked for distribution of a lean crc executable as I see potential for confusion & complication. I just want to be able to build a lean crc executable by (and for) myself.

Maybe the second part of my issue still stands. It would be great if you could add the information given by @cfergeau to `developing.adoc` (or some other appropriate document), i.e. semantics of `make` vs. `make embed_bundle`.

**Comment by gbraad** [comment]
right, we haven't focussed on those parts of the documentation as the process to involve in the development is not that easy. mostly due to the bits not 'easily available' for the cluster image generation.

but we will certainly work on this.

however, the distribution is discussible. we are in dealing with installers in the future to setup the system integration, and in that case the oversized binaries is an unwanted side-effect.

be aware, that `make cross` is likely a better option to ensure changes word across the board.
