### ISSUE TITLE
Enhancement request:  Support for multiple clusters

### ISSUE THREAD

**Issue by crobby** [code-ready/crc#935]
I have a scenario where I'm testing a particular feature that can be installed in multiple ways.  Right now, in order to test each scenario, I have to tear down and re-create my cluster each time.

I do not need the clusters to be active concurrently (Pretty sure that would melt my laptop anyway).

Is there a way that I could have cluster A spun up and working, but then shut that cluster down and put it aside for some time while spinning-up cluster B and using it for awhile before shutting it down and bringing cluster A back up?

I suppose I could maybe make this happen by saving off the VM that is spun-up, and spinning up a new one and then switching those files around as needed, but that seems clumsy and error-prone.

Thanks for the consideration.

**Comment by cfergeau** [comment]
> I suppose I could maybe make this happen by saving off the VM that is spun-up, and spinning up a new one and then switching those files around as needed, but that seems clumsy and error-prone.

This is going to be your best option for now ;)

**Comment by gbraad** [comment]
We will not be adding a way to add multiple clusters. This is because the resource usage is too much to make this practical for the average user. (This is an advanced user scenario).

You could try to play around with the `constants.go` and redefine `crc` to be named differently (so using multiple binaries or even exposing this, but you will run into other issues as the clusters are not unique

**Comment by gbraad** [comment]
Note: you would benefit more from deployment scripts and snapshots (but these will not be enabled from CRC as they can cause issues for new users).
