### ISSUE TITLE
Socks5 proxy support on macOS

### ISSUE THREAD

**Issue by opuk** [code-ready/crc#938]
### General information

  * OS: macOS
  * Hypervisor: KVM / Hyper-V / hyperkit
  * Did you run `crc setup` before starting it (Yes/No)? No, it fails

## CRC version
```bash
crc version: 1.4.0+d5bb3a3
OpenShift version: 4.2.13 (embedded in binary)

```
  
## CRC status
```bash
# Put the output of `crc status`
```

## CRC config
```bash
empty
```

## Host Operating System
```bash
ProductName:    Mac OS X
ProductVersion: 10.15.2
BuildVersion:   19C57
```

### Steps to reproduce

  1. Configure macOS to use a socks5 proxy
  2. Try run crc setup

### Expected
CRC should support systems configured with socks5 proxy in restricted environments that requires it.

### Actual
Proxy URL 'socks5h://10.2.0.4:1080' is not valid.

**Comment by gbraad** [comment]
Implementing SOCKS5 support would mean we need to implement some translation, since AFAIK OpenShift does not support this. All the commands and containers deal with simple HTTP-based proxy support IIRC.

Somehow, I feel this is outside of the scope of CRC as these kind of tools exist and address a very specific need. I'll get back to this.
