### ISSUE TITLE
Another "works on x86_64 only" -project

### ISSUE THREAD

**Issue by c5253458** [code-ready/crc#957]

**Comment by gbraad** [comment]
If OpenShift and RHCOS are available as non-X86 offerings, with a viable virtual machine target on a host that fits our model, we will certainly want to platforms like PPC or ARM. But at the moment, the @code-ready/crc-devel team does not readily have access to hardware for this. We are mostly reliant on the hardware enablement teams to also provide a solution for CRC, but so far they have asked about this, but not offered assistance.

**Comment by c5253458** [comment]
You can freely test your open source software on more target CPU architectures.

Travis CI can now run your Linux builds on IBM Power and IBM Z CPU architectures on top of already available amd64 and arm64 (ARMv8).
( https://changelog.travis-ci.com/building-on-ibm-power-and-ibm-z-cpu-architectures-126959 )

**Comment by gbraad** [comment]
Travis does not do nested virtualization, so this won't help us

**Comment by c5253458** [comment]
So plain root-access to several hosts would be perfect for each targeted hardware platform ?

Are virtual machines on that platforms sufficient, too ?

I feel lots of platforms and software developed nowadays targets commercial benefits too early and restrict use for the development of open source software.

Especially the direction towards open-source means linux on x86_64 is harmful, for example when you envision the internet of things, where a much bigger number of hardware-platforms can be expected.

**Comment by c5253458** [comment]
OSU Open Source Lab provides free direct access to the hardware platforms as well as jenkins Continuous Integration:

* [IBM Z Development Hosting](https://osuosl.org/services/ibm-z/)
* [POWER Development Hosting](https://osuosl.org/services/powerdev/)

Does that satisfy your project's requirements ?

**Comment by gbraad** [comment]
I would have to examine if this offers what we want. Red Hat already works with them for enablement but at the moment we have #978 which prevents releasing

> I feel lots of platforms and software developed nowadays targets commercial benefits too early 

We have to weigh ROI as we are targeting a specific usecase to enable developers. At the moment we have to prioritize according to the numbers, and these indicate that the majority of people either have a macOS or Windows based machine. At the moment we are pretty much in the productization phase which means we only have bandwidth to target these main platforms first, which will be case until the end of the current quarter for sure.

Note: We would have to redo the work to create a SNC:
https://docs.openshift.com/container-platform/4.2/installing/installing_ibm_z/installing-ibm-z.html#minimum-resource-requirements_installing-ibm-z since the default assumes a HA setup. Are you willing to provide patches?

**Comment by zhengxiaomei123** [comment]
> Note: We would have to redo the work to create a SNC:
> https://docs.openshift.com/container-platform/4.2/installing/installing_ibm_z/installing-ibm-z.html#minimum-resource-requirements_installing-ibm-z since the default assumes a HA setup. Are you willing to provide patches?

Is there an issue to define this work?

**Comment by gbraad** [comment]
No, as this implementation specific and our primary goal is to serve a development and testing environment for notebook use. The need to run on IBM Z did not easily fall into that category so also did not end up as an issue to track this work. You are free to create one, but this would be best to be part of a code-ready/snc fork that targets this creation process first.

**Comment by mtarsel** [comment]
hello, I created https://github.com/code-ready/snc/pull/209 to address s390x and ppc64le. Since 4.3 the mirror now contains the binaries for IBM's arches. Please reach out to me on slack if you have any questions. I have been talking with @zhengxiaomei123 via email about this.

**Comment by gbraad** [comment]
https://github.com/code-ready/snc/pull/209 has been merged now
